{% set version = "1.5" %}

package:
  name: holoviews
  version: {{ version }}

source:
  git_url: https://github.com/ioam/holoviews.git
  git_tag: 91cdeee464973a7dc1b6e351bcf8cd8a94a4e7e7


build:
  number: 0

requirements:
  build:
    - python
    - scipy
    - numpy <=1.9.3
    - freetype <=2.5.2
    - nose
    - matplotlib <1.5
    - bokeh
    - pandas
    - notebook
    - param
  run:
    - python
    - scipy
    - numpy <=1.9.3 
    - freetype <=2.5.2
    - nose
    - matplotlib <1.5
    - bokeh
    - pandas
    - notebook
    - param

test:
  imports:
    - holoviews

about:
  home: https://github.com/conda-forge/staged-recipes
  license: BSD
  summary: annotate your data and let it visualize itself

extra:
  recipe-maintainers:
    - marqh
    - philippjfr
    - jlstevens
