# Jinja variables help maintain the recipe as you'll update the version only here.
{% set version = "0.3" %}

package:
    name: nbopen
    version: {{ version }}

source:
    fn: nbopen-{{ version }}.tar.gz
    url: https://github.com/takluyver/nbopen/archive/{{ version }}.tar.gz
    sha256: 485c0a5c53e7ee3d849abf88f53c151057f01e19b6ad7fec92879edd7017b405

build:
    number: 0
    # If the installation is complex, or different between Unix and Windows, use separate bld.bat and build.sh files instead of this key.
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
    run:
        - python

test:
    # Some package might need a `test/commands` key to check CLI.
    imports:
        - nbopen

about:
    home: https://github.com/takluyver/nbopen
    license: BSD
    summary: 'Open notebooks from the command line'

extra:
    recipe-maintainers:
        - marqh
        - takluyver
